### ISSUE TITLE
settings don't show even when plugin is activated.

### ISSUE THREAD

**Issue by MajorSlug** [Pheneeny/CuraPlugin-ScalableExtraPrime#3]
On Cura 3.2.1

Settings fields are well set visible:
![image](https://user-images.githubusercontent.com/37349730/37996682-c79baffe-3218-11e8-8cf7-a2a7fcdbdf3f.png)

But don't show up.

![image](https://user-images.githubusercontent.com/37349730/37996628-9abf54f4-3218-11e8-9710-f2ab4fed578e.png)

To access them, I need to use the "search..." bar.

![image](https://user-images.githubusercontent.com/37349730/37996727-ede599ea-3218-11e8-8948-12388e81c111.png)

**Comment by rooiejoris** [comment]
same here, could this be in relation with the json file...?!

cheers / joris

**Comment by Pheneeny** [comment]
I don't know the root cause of the issue, but I know that if you collapse the "Material" category completely and re-expand it, the settings will show up properly from then on.

I apologize for the late response, I did not have my notifications configured in Github correctly and was never notified of your issue.

**Comment by MajorSlug** [comment]
Thanks for the tip.
